FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./app ./app

ENV INSTANCE_NAME="gateway"


CMD ["uvicorn", "app.security.gateway:app", "--host", "0.0.0.0", "--port", "8080"]
